# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Application Layouts with Flex Box
email: design@ianwremmel.com
description: >
  Application Layouts with Flex Box
baseurl: "flexbox-layouts"
url: "https://ianwremmel.github.io/" # the base hostname & protocol for your site
twitter_username: ianwremmel
github_username:  ianwremmel

# Build settings
markdown: kramdown

kramdown:
  input: GFM
